[environment]
extra-paths = ["./gguf-py", "./examples/model-conversion/scripts", "./scripts/snapdragon/qdc/tests"]
python-version = "3.10"

[rules]
deprecated = "warn"

[[overrides]]
include = [
    "./scripts/snapdragon/qdc/**",
]

[overrides.rules]
unresolved-reference = "ignore"
unresolved-import = "ignore"
unresolved-attribute = "ignore"
